"""update VideoStats table

Revision ID: 33c40587e994
Revises: 5028f892092c
Create Date: 2025-06-06 15:12:05.380543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33c40587e994'
down_revision: Union[str, None] = '5028f892092c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the old primary key constraint
    op.drop_constraint('video_stats_pkey', 'video_stats', type_='primary')

    # Create new composite primary key
    op.create_primary_key('video_stats_pkey', 'video_stats', ['video_id', 'trending_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop composite PK
    op.drop_constraint('video_stats_pkey', 'video_stats', type_='primary')

    # Recreate old PK
    op.create_primary_key('video_stats_pkey', 'video_stats', ['video_id'])
    # ### end Alembic commands ###
