"""add channel statistics

Revision ID: 4eb5237e5ede
Revises: 33c40587e994
Create Date: 2025-09-11 19:16:25.406550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eb5237e5ede'
down_revision: Union[str, None] = '33c40587e994'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_statistics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('fetch_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('subscriber_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channel_infos.channel_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('top_channels')
    op.drop_table('trending_streak')
    op.drop_table('popular_category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('popular_category',
    sa.Column('category_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('video_count', sa.BIGINT(), autoincrement=False, nullable=True)
    )
    op.create_table('trending_streak',
    sa.Column('video_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('day_streak', sa.BIGINT(), autoincrement=False, nullable=True)
    )
    op.create_table('top_channels',
    sa.Column('channel_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('channel_title', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.drop_table('channel_statistics')
    # ### end Alembic commands ###
