"""create RawYoutubeTrending, VideoCategory, ChannelInfo, VideoStats tables

Revision ID: 5028f892092c
Revises: 
Create Date: 2025-05-14 14:49:19.172819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5028f892092c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_infos',
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('channel_title', sa.Text(), nullable=False),
    sa.Column('country', sa.Text(), nullable=False),
    sa.Column('published_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('channel_id')
    )
    op.create_table('raw_youtube_trending',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('raw_json', sa.JSON(), nullable=False),
    sa.Column('fetch_timestamp', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_categories',
    sa.Column('category_id', sa.String(), nullable=False),
    sa.Column('category_name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('video_stats',
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('published_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('trending_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['video_categories.category_id'], ),
    sa.ForeignKeyConstraint(['channel_id'], ['channel_infos.channel_id'], ),
    sa.PrimaryKeyConstraint('video_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_stats')
    op.drop_table('video_categories')
    op.drop_table('raw_youtube_trending')
    op.drop_table('channel_infos')
    # ### end Alembic commands ###
