"""update channel statistics fetch timestamp

Revision ID: 8de783d03248
Revises: f1fa1febcfc9
Create Date: 2025-09-11 21:40:57.800478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8de783d03248'
down_revision: Union[str, None] = 'f1fa1febcfc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel_statistics', sa.Column('fetch_timestamp', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('channel_statistics', 'fetch_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel_statistics', sa.Column('fetch_date', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=False))
    op.drop_column('channel_statistics', 'fetch_timestamp')
    # ### end Alembic commands ###
