"""update channel statistics video count

Revision ID: f1fa1febcfc9
Revises: c8b80d94a7a9
Create Date: 2025-09-11 21:35:23.132034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1fa1febcfc9'
down_revision: Union[str, None] = 'c8b80d94a7a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel_statistics', sa.Column('video_count', sa.BigInteger(), nullable=True))
    op.drop_column('channel_statistics', 'like_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel_statistics', sa.Column('like_count', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('channel_statistics', 'video_count')
    # ### end Alembic commands ###
