version: 2

models:
  - name: trending_streak
    description: "Video which has more than 1 trending date"
    columns:
      - name: video_id
        description: "The primary key for this table"
        data_tests:
          - not_null
      - name: day_streak
        description: "The title of the video"
        data_tests:
          - not_null
          - relationships:
              to: ref('video_stats')
              field: video_id
  - name: popular_category
    description: "Top 10 category"
    columns:
        - name: category_id
          description: "The primary key for this table"
          data_tests:
            - not_null
        - name: category_name
          description: "Name of category"
          data_tests:
            - not_null
        - name: video_count
          description: "Number of video counted by category"
          data_tests:
              - not_null
